<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?=$title?></title>
  <link rel="shortcut icon" href="/img/favicon.svg" type="image/x-icon">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <script src="https://kit.fontawesome.com/416685e231.js" crossorigin="anonymous"></script>

</head>

<body>
  <div class="container-father">
    <nav class="navbar navbar-inverse" id="menu">
      <div class="container-fluid" id="nav-container">
        <div class="navbar-header" id="nav-header">
          <a class="navbar-brand" href="/agendaPhp/home" id="main-link">
            <span class="glyphicon glyphicon-earphone" style=" margin-right: 0.4em;"></span>
            Agenda
          </a>
        </div>
        <ul class="nav navbar-nav" s id="home-link">
          <?php if (isset($_SESSION['id'])) {

            echo '<li><a href="/agendaPhp/contacts">Contatos</a></li>';
            echo '<li><a href="/agendaPhp/groups">Grupos</a></li>';
            echo '<li><a href="/agendaPhp/events">Eventos</a></li>';
          } ?>

        </ul>
        <ul class="nav navbar-nav navbar-right" id="nav-right">

          <li class="config-bttn">
            <?php if (isset($_SESSION['id'])) {

              echo  '<a href="" class="dropdown-toggle" id="nav-bttn" data-toggle="dropdown">';
              echo "<p>{$_SESSION['name']}</p>";
              echo   "<span class='glyphicon glyphicon-user'></span>";
              echo '</a>';
            } ?>
            <ul class="dropdown-menu" style="padding: 10px;">
              <li><a href="/agendaPhp/editUser"><span class="glyphicon glyphicon-cog" style="margin-bottom: 10px;"></span>
                  Configurações</a></li>
              <li><a href="/agendaPhp/logout"><span class="glyphicon glyphicon-log-out"></span> Sair</a></li>
            </ul>
          </li>
          <?php if (!isset($_SESSION['id'])) {
            echo '<li><a href="/agendaPhp/login"></span> Login</a></li>';
            echo '<li><a href="/agendaPhp/register"></span> Register</a></li>';
          } ?>
        </ul>
      </div>
    </nav>
    <div style="padding: 5em">
    <?php if(!isset($_SESSION['id']) && !is_null($message)){
               echo '<div class="message-container">';
                echo    '<div class="message">';
                       if(isset($message)) echo $message;
                    echo'</div>';
                    echo'</div>';
            }?>
    <div class="container">
    <h1 style="font-size: x-large;  font-weight: 700;">Remover contatos de: {{groups.name}}</h1>
    <form action="/groups_contacts/removeContacts" method="post" class="form-add">
        <input type="hidden" name="idGroup" value="{{groups.id}}">
        <div class="checklist-container">
            {{#each groups.Contacts}}
            <label class="container-checkbox">{{this.name}} - {{this.email}}
                <input type="checkbox" name="contacts" id="contacts" value="{{this.id}}">
                <span class="checkmark"></span>
            </label>
            {{/each}}
        </div>
        <input type="submit" value="Remover" id="bttn-contact">
    </form>
</div>
    </div>
  </div>
  <footer>
    <p><span>Agenda</span> &copy; 2022
    <p style="margin-left: 2px;">By <a rel="author" target="_blank" href="https://www.linkedin.com/in/caique-araújo-0053201b0/" id="linkedin-link">Caique Araújo</a></p>
    </p>
  </footer>
</body>
<style><?php include './views/templates/style.css'; ?></style>
</html>