<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contacts</title>
    <link rel="shortcut icon" href="/img/favicon.svg" type="image/x-icon">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/416685e231.js" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container-father">
        <nav class="navbar navbar-inverse" id="menu">
            <div class="container-fluid" id="nav-container">
                <div class="navbar-header" id="nav-header">
                    <a class="navbar-brand" href="/agendaPhp/home" id="main-link">
                        <span class="glyphicon glyphicon-earphone" style=" margin-right: 0.4em;"></span>
                        Agenda
                    </a>
                </div>
                <ul class="nav navbar-nav" s id="home-link">
                    <?php if (isset($_SESSION['id'])) {

                        echo '<li><a href="/agendaPhp/contacts">Contatos</a></li>';
                        echo '<li><a href="/agendaPhp/groups">Grupos</a></li>';
                        echo '<li><a href="/agendaPhp/events">Eventos</a></li>';
                    } ?>

                </ul>
                <ul class="nav navbar-nav navbar-right" id="nav-right">

                    <li class="config-bttn">
                        <?php if (isset($_SESSION['id'])) {


                            echo  '<a href="" class="dropdown-toggle" id="nav-bttn" data-toggle="dropdown">';
                            echo "<p>{$_SESSION['name']}</p>";
                            echo   "<span class='glyphicon glyphicon-user'></span>";
                            echo '</a>';
                        } ?>



                        <ul class="dropdown-menu" style="padding: 10px;">

                            <li><a href="/agendaPhp/editUser"><span class="glyphicon glyphicon-cog" style="margin-bottom: 10px;"></span>
                                    Configurações</a></li>
                            <li><a href="/agendaPhp/logout"><span class="glyphicon glyphicon-log-out"></span> Sair</a></li>
                        </ul>

                    </li>
                    <?php if (!isset($_SESSION['id'])) {

                        echo '<li><a href="/agendaPhp/login"></span> Login</a></li>';
                        echo '<li><a href="/agendaPhp/register"></span> Register</a></li>';
                    } ?>

                </ul>
            </div>
        </nav>
        <div style="padding: 5em">
        <?php if(!isset($_SESSION['id']) && !is_null($message)){
               echo '<div class="message-container">';
                echo    '<div class="message">';
                       if(isset($message)) echo $message;
                    echo'</div>';
                    echo'</div>';
            }?>
            <div class="container-lists">
            <script> var message = 'Deseja confirmar a exclusão ?'; </script>

                <div class="sub-container">
                    <div class="bttn-links">
                        <a class="bttn-add" href="/agendaPhp/addGroup">Adicionar grupos</a>
                    </div>
                    <h1>Grupos</h1>
                    <div class="models-container">

                    <?php

                        foreach ($groups as $group) {
                            echo "
                            <div class='models-sub-container'>
                                <div class='container-data'>
                                    <p><span class='bold'>{$group['name']}</a></span></p>
                                    <p class='data-p'><span style='font-weight: 600;'>Descrição:</span> {$group['description']}</p>
                                    <p class='data-p'><span style='font-weight: 600;'>Contatos:</span>
                                        <span style='margin-right: auto;'>
                                            <span style='color: blue;'>|</span>
                                        </span>
                                    </p>
                                </div>
                                <div class='container-options'>
                                    <a id='bttn-edit' href='/agendaPhp/editGroup/{$group['id']}'></a>
                                    <form action='/agendaPhp/deleteGroup' method='post'>
                                        <input type='hidden' name='id' value='{$group['id']}'>
                                        <input type='submit' id='bttn-delete' value='' onClick='return confirm(message)'>
                                    </form>
                                    <a href='/agendaPhp/addContactGroup/{$group['id']}' id='bttn-addContact'></a>
                                    <a href='/agendaPhp/removeContactGroup/{$group['id']}' id='bttn-deleteContact'></a>
                                </div>
                            </div>";
                        }
                    ?>
                    </div>
                </div>
            </div>
            </div>
        <footer>
            <p><span>Agenda</span> &copy; 2022
            <p style="margin-left: 2px;">By <a rel="author" target="_blank" href="https://www.linkedin.com/in/caique-araújo-0053201b0/" id="linkedin-link">Caique Araújo</a></p>
            </p>
        </footer>
</body>
<style><?php include './views/templates/style.css'; ?></style>

</html>