<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contacts</title>
    <link rel="shortcut icon" href="/img/favicon.svg" type="image/x-icon">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/416685e231.js" crossorigin="anonymous"></script>

</head>

<body>
    <div class="container-father">
        <nav class="navbar navbar-inverse" id="menu">
            <div class="container-fluid" id="nav-container">
                <div class="navbar-header" id="nav-header">
                    <a class="navbar-brand" href="/agendaPhp/home" id="main-link">
                        <span class="glyphicon glyphicon-earphone" style=" margin-right: 0.4em;"></span>
                        Agenda
                    </a>
                </div>
                <ul class="nav navbar-nav" s id="home-link">
                    <?php if (isset($_SESSION['id'])) {

                        echo '<li><a href="/agendaPhp/contacts">Contatos</a></li>';
                        echo '<li><a href="/agendaPhp/groups">Grupos</a></li>';
                        echo '<li><a href="/agendaPhp/events">Eventos</a></li>';
                    } ?>

                </ul>
                <ul class="nav navbar-nav navbar-right" id="nav-right">

                    <li class="config-bttn">
                        <?php if (isset($_SESSION['id'])) {


                            echo  '<a href="" class="dropdown-toggle" id="nav-bttn" data-toggle="dropdown">';
                            echo   '<span class="glyphicon glyphicon-user"></span>';
                            echo '</a>';
                        } ?>



                        <ul class="dropdown-menu" style="padding: 10px;">

                            <li><a href="/agendaPhp/editUser"><span class="glyphicon glyphicon-cog" style="margin-bottom: 10px;"></span>
                                    Configurações</a></li>
                            <li><a href="/agendaPhp/logout"><span class="glyphicon glyphicon-log-out"></span> Sair</a></li>
                        </ul>

                    </li>
                    <?php if (!isset($_SESSION['id'])) {

                        echo '<li><a href="/agendaPhp/login"></span> Login</a></li>';
                        echo '<li><a href="/agendaPhp/register"></span> Register</a></li>';
                    } ?>

                </ul>
            </div>
        </nav>

        <div style="padding: 5em">

            <div class="container-lists">

                <div class="sub-container">
                    <div class="bttn-links">
                        <a class="bttn-add" href="/agendaPhp/addContact">Adicionar contatos</a>
                    </div>
                    <h1><?= $title?></h1>
                    <div class="models-container">
                        <?php 
                        
                        foreach ($contacts as $contact) {


                            echo "<div class='models-sub-container'>
                            <div class='container-data'>
                                <p><span class='bold'>{$contact['name']}</span></p>
                                <p class='data-p'><span style='font-weight: 600;'>Telefone:</span>{$contact['fone']}</p>
                                <p class='data-p'><span style='font-weight: 600;'>Email:</span>{$contact['email']}</p>
                            </div>
                            <div class='container-options'>
                                <a id='bttn-edit' href='/agendaPhp/editContact/{$contact['id']}'></a>
                                <form action='/agendaPhp/deleteContact' method='post'>
                                    <input type='hidden' name='id' value='{$contact['id']}'>
                                    <input type='submit' id='bttn-delete' value=''>
                                </form>
                            </div>
                        </div>";
                        } ?>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer>
        <p><span>Agenda</span> &copy; 2022
        <p style="margin-left: 2px;">By <a rel="author" target="_blank" href="https://www.linkedin.com/in/caique-araújo-0053201b0/" id="linkedin-link">Caique Araújo</a></p>
        </p>
    </footer>
</body>
<style>
    * {
        font-family: 'Poppins', sans-serif;
        font-weight: 400;
        padding: 0;
        margin: 0;
    }

    body {
        background-attachment: fixed;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
        overflow: auto;

    }

    .container-father {
        padding: 0;
        padding-bottom: 5em;
        top: 0;
        width: 100vw;
        height: 100vh;
        display: block;
        overflow-y: scroll;
        flex-direction: column;
    }


    #nav-container {
        width: 100vw;
        display: flex;
        justify-content: space-between;
    }

    #nav-container #nav-header {
        margin-left: 0;
        margin-right: auto;
    }

    #nav-container #nav-right {
        margin-right: 0;
        margin-left: auto;
    }

    #menu {
        background-color: #13293d;
        border-radius: 0;
        margin-top: 0;
        margin-bottom: 0;
        display: flex;
        justify-content: space-between;
        width: 100vw;
    }



    a {
        text-decoration: none;
        color: rgb(60, 60, 60);
    }


    a:visited {
        color: black;
    }


    a:hover {
        color: rgb(112, 112, 112);
        text-decoration: none;
    }

    #nav-container {
        width: 100%;
        display: flex;
        justify-content: space-between;
    }

    #dropdown-bttn:hover {
        color: white;
    }


    #nav-header {
        padding-left: 1em;
        position: left;
        right: 0;
    }

    #main-link {
        display: flex;
        justify-content: center;
        align-items: center;
        color: #9d9d9d;
    }

    #main-link:hover {
        color: white;
    }

    #name-link {
        font-size: large;
        font-weight: 600;
        color: black;
    }

    #name-link:hover {
        color: rgb(110, 110, 110);
    }

    #nav-bttn p {
        padding: 0;
        margin: auto 0.8em;
    }

    #linkedin-link {
        color: #7c7c7c;
        text-decoration: none;
    }

    #linkedin-link:hover {
        color: #ffffff;
        font-weight: 500;
    }



    footer {

        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        height: 5em;
        display: flex;
        align-items: center;
        justify-content: center;
        border-top: 1px solid #8a8a8a;
        background-color: #13293d;
    }

    footer p {
        color: #7c7c7c;
    }

    footer span {
        font-weight: bold;
        color: rgb(212, 212, 212);
    }
    .bttn-add{
    padding: 5px 16px;
    background-color: rgba(195, 195, 195, 0.4);  
    box-shadow: 0px 1.5px 5px 0px rgba(0,0,0,0.23);
    color: #091420;
    backdrop-filter: blur(7px);
    border: 1px solid transparent;
    border-radius: 5px;
    font-weight: 600;
    font-size: medium;
}


.bttn-add:visited{
    color: #091420;
}

.bttn-add:visited:hover{
    color: #1c3046;
    background-color: rgba(247, 247, 247, 0.4);  

}
    .bttn-links{
    width: auto;
    padding: 10px;
    display: flex;
    justify-content: center;
    align-items: center;
}

.bttn-links #bttn-contact{
    margin-right: 10px;
}
.models-container{
    border-top: 1px solid #13293d;
    width: 100%;
    padding: 10px;
    margin: 5px;
}


.models-container .models-sub-container {
    border-bottom: 1px solid #ccc;
}

.models-container div:last-child {
    border-bottom: 1px solid transparent;
}
    .container-lists{
    display: flex;
    margin: auto;
    flex-direction: column;
    align-items: center;
}
.sub-container{
    min-height: 300px;
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 70vw;
    margin: 10% auto;
    padding: 20px;
    background-color: rgba(255, 255, 255, 0.55);  
    box-shadow: 0px 1.5px 5px 0px rgba(0,0,0,0.23);
    backdrop-filter: blur(20px);
    border-radius: 10px;
}
.sub-container h1{
    padding: 0em 0.5em;
    margin: 0.5em 0;

}
.sub-container .bttn-links{
    margin-left: 0;
    margin-right: auto;
}

.message-container + .container{
    margin-bottom: 20px;
}

.models-sub-container{
    background-color: rgba(195, 195, 195, 0.4);
    box-shadow: 0px 1.5px 5px 0px rgba(0,0,0,0.23);
    margin-bottom: 0.7em;
    border-radius: 10px;
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    padding: 5px 10px;
}

.models-sub-container:first-child{
    margin-top: 2em;
}

.container-options{
    display: flex;
    flex-direction: row;
    justify-content: center;
    padding: 0.3em;
}

.container-data{
    padding: 0.3em;
}

.container-data p{
    padding: 0;
}

.data-p{
    font-size: medium;
    font-weight: 500;
}

#bttn-edit{
    margin-right: 0.3em;/*
    background: rgba(0,0,0,0) url(../../public/img/editIcon.svg);
    background-position: center; 
    background-size: cover; */
    
    width: 20px;
    height: 20px;
    background-color: #091420;
}


#bttn-delete{
    /*background-image:rgba(0,0,0,0) url(../../public/img/deleteIcon.svg);
    background-position: center; 
    background-repeat: no-repeat; 
    background-size: cover; */
    width: 20px;
    height: 20px;
    background-color: black;
}

#bttn-deleteContact{
    background-image: url(../../public/img/removeContact.svg);
    background-position: center; 
    background-repeat: no-repeat; 
    background-size: cover; 
    width: 20px;
    height: 20px;
    background-color: transparent;
}


#bttn-addContact{
    margin-left: 0.7em;
    margin-right: 0.3em;
    background-image: url(../../public/img/addContact.svg);
    background-position: center; 
    background-repeat: no-repeat; 
    background-size: cover; 
    width: 20px;
    height: 20px;
    background-color: transparent;
}

#bttn-edit:hover,#bttn-addContact:hover,#bttn-deleteContact:hover,#bttn-delete:hover{
    filter: invert(52%) sepia(0%) saturate(1%) hue-rotate(202deg) brightness(92%) contrast(83%);
}



#bttn-password{

    background-color: transparent;
    color: #091420;
    font-size: medium;
    font-weight: 600;
    margin: 0.3em;
}

#bttn-password:hover{
    color: #7c7c7c;
}

#p-password{

    background-color: transparent;
    color: #515151  ;
    font-size: medium;
    font-weight: 500;
    margin: 0.3em;
}

.bold {
    font-size: large;
    font-weight: 600;
    color: black;
}
</style>

</html>