<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $titulo ?></title>
    <link rel="shortcut icon" href="/img/favicon.svg" type="image/x-icon">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/416685e231.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="../../public/css/style.css">
</head>

<body>
    <div class="container-father">
        <nav class="navbar navbar-inverse" id="menu">
            <div class="container-fluid" id="nav-container">
                <div class="navbar-header" id="nav-header">
                    <a class="navbar-brand" href="/" id="main-link">
                        <span class="glyphicon glyphicon-earphone" style=" margin-right: 0.4em;"></span>
                        Agenda
                    </a>
                </div>
                <ul class="nav navbar-nav" s id="home-link">
                    <li><a href="/contacts/contacts">Contatos</a></li>
                    <li><a href="/groups/groups">Grupos</a></li>
                    <li><a href="/events/events">Eventos</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right" id="nav-right">

                    <li class="config-bttn">

                        <a href="" class="dropdown-toggle" id="nav-bttn" data-toggle="dropdown">
                            <span class="glyphicon glyphicon-user"></span>
                        </a>

                        <ul class="dropdown-menu" style="padding: 10px;">
                            <li><a href="/users/config"><span class="glyphicon glyphicon-cog"
                                        style="margin-bottom: 10px;"></span>
                                    Configurações</a></li>
                            <li><a href="/users/logout"><span class="glyphicon glyphicon-log-out"></span> Sair</a></li>
                        </ul>
                    </li>
                    <li><a href="/users/login"></span> Login</a></li>
                    <li><a href="/users/register"></span> Register</a></li>
                </ul>
            </div>
        </nav>
        <div class="message-container">
            <div class="message">
            </div>
        </div>

       <!-- <?= $conteudo ?> -->
    </div>
    <footer>
        <p><span>Agenda</span> &copy; 2022
        <p style="margin-left: 2px;">By <a rel="author" target="_blank"
                href="https://www.linkedin.com/in/caique-araújo-0053201b0/" id="linkedin-link">Caique Araújo</a></p>
        </p>
    </footer>
</body>


</html>